name: action-check-workflow-wait
description: https://github.com/champ-oss/action-check-workflow-wait
inputs:
  GH_INSTALLATION_ID:
    description: 'github installation id'
    required: true
  GH_WORKFLOW:
    description: 'github workflow to wait on'
    required: true
  GH_APP_ID:
    description: 'github app id'
    required: true
  GH_APP_PRIVATE_KEY:
    description: 'github app private key'
    required: true
runs:
  using: "composite"
  steps:
    - name: install jira lib
      shell: bash
      run: cd ${{github.action_path}} && pip3 install -r requirements.txt
    - name: run python script
      shell: bash
      run: |
        python3 ${GITHUB_ACTION_PATH}/action.py